### ISSUE TITLE
Reboot/wake with proxy set crashes proxyunsetter

### ISSUE THREAD

**Issue by ghost** [tjeerdhans/proxyunsetter#3]
If the proxy is set by a policy from a whitelisted ipaddress waking up from sleep or rebooting causes proxyunsetter to crash.

**Comment by tjeerdhans** [comment]
Any crash details? Anyway, the improved exception handling should shed some more light on the issue.

**Comment by tjeerdhans** [comment]
Should be fixed in 1.4.
