### ISSUE TITLE
Windows 10 issue

### ISSUE THREAD

**Issue by Suleman-Elahi** [tjeerdhans/proxyunsetter#6]
On my Windows 10, Build  15063.726, the software was unable to throw desktop notifications. However, it is able to revert the proxy settings successfully.

**Comment by tjeerdhans** [comment]
Hi, are you sure 'Notify when proxy set' was enabled in the settings?

![image](https://user-images.githubusercontent.com/306113/33318907-c0ed2348-d43c-11e7-8184-ca7f49d495fc.png)

**Comment by tjeerdhans** [comment]
Hi, did you write this article?
http://www.ilovefreesoftware.com/05/tutorial/how-to-automatically-revert-changes-to-system-proxy-in-windows-10.html

If so, thanks!
